import { Providers } from '@/providers';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Clarity from '@microsoft/clarity';

import '@/styles/globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  if (process.env.NEXT_CLARITY_ID) {
    Clarity.init(process.env.NEXT_CLARITY_ID);
  }

  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
